export const IPC = {
	initialConfig: 'review:initial-config',
	history: 'review:history',
	clearHistory: 'review:clear-history',
	rangeState: 'review:range-state',
	rangeOpenItem: 'review:range-open-item',
	rangeSetReviewed: 'review:range-set-reviewed',
	chooseRoot: 'review:choose-root',
	validateConfig: 'review:validate-config',
	start: 'review:start',
	reload: 'review:reload',
	close: 'review:close',
	manifest: 'review:manifest',
	loadFile: 'review:load-file',
	prioritizeHunk: 'review:prioritize-hunk',
	prioritizeFile: 'review:prioritize-file',
	analyzeAnyway: 'review:analyze-anyway',
	retry: 'review:retry',
	search: 'review:search',
	cancelSearch: 'review:cancel-search',
	getQa: 'review:get-qa',
	askHunk: 'review:ask-hunk',
	cancelQa: 'review:cancel-qa',
	buildStory: 'review:build-story',
	enterStory: 'review:enter-story',
	navigateStory: 'review:navigate-story',
	stopStory: 'review:stop-story',
	cacheInfo: 'review:cache-info',
	clearCache: 'review:clear-cache',
	speechGetSettings: 'speech:get-settings',
	speechSetSettings: 'speech:set-settings',
	speechModelStatus: 'speech:model-status',
	speechDownloadModel: 'speech:download-model',
	speechSiriStatus: 'speech:siri-status',
	speechVoiceboxStatus: 'speech:voicebox-status',
	speechPlayRole: 'speech:play-role',
	speechPrepare: 'speech:prepare',
	speechIsCached: 'speech:is-cached',
	speechStop: 'speech:stop',
	speechPause: 'speech:pause',
	speechResume: 'speech:resume',
	speechCacheInfo: 'speech:cache-info',
	speechClearCache: 'speech:clear-cache',
	speechEvent: 'speech:event',
	event: 'review:event'
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
